### ISSUE TITLE
add environment variables to the created airflow-worker pod

### ISSUE THREAD

**Issue by sayakin0519** [awslabs/data-on-eks#472]
- [O] ✋ I have searched the open/closed issues and my issue is not listed.

#### Please describe your question here

Hi. I have a question about self-managed-airflow

I want to add environment variables to the created airflow-worker pod. 

This is because we are trying to insert environment variables for gcp bigquery integration into the pod. 

Even if I used various resource forms in airflow-core.tf, it didn't work, and even if I tried it in airflow-values.yaml in the helm-values folder, it didn't work.

When I entered exec in Pods and entered the export or env command, the environment variables I defined did not appear.

How can I add environment variables into pods? (It is not very efficient to enter the pods one by one and enter environment variables using export.)

**Comment by vara-bonthu** [comment]
@jagpk 👆

**Comment by sayakin0519** [comment]
> @jagpk 👆
May I know when the person you mentioned will reply?
Or is there anyone else who can solve this problem?

Thanks.

**Comment by jagpk** [comment]
@sayakin0519 - are you running Airflow on EKS or GKE? Have you tried setting Environment variables for all airflow containers in values.yaml? Refer this -   https://github.com/apache/airflow/blob/main/chart/values.yaml#L272 ?

**Comment by sayakin0519** [comment]
> @sayakin0519 - are you running Airflow on EKS or GKE? Have you tried setting Environment variables for all airflow containers in values.yaml? Refer this - https://github.com/apache/airflow/blob/main/chart/values.yaml#L272 ?

I'm running Airflow at EKS. 
but i'm using "apache-airflow-providers-google", "apache-airflow-providers-mysql" 
package in my DAG

So, Yes. I tried that option like this (Example)

```yaml
airflow: 
  env: 
    - name: AIRFLOW_CONN_GOOGLE_CLOUD_DEFAULT
      value: "google-cloud-platform://extra__google_cloud_platform__key_path=/~~~~~~"
    - name: AIRFLOW_CONN_MYSQL_MYDBNAME
      value: "mysql://mydbname:password@mysql"
```

After add that code in airflow-values.yaml and I entered this command again. "./install.sh"

And I entered the pod with this command and looked at env, but it was not there.
"kubectl exec -n airflow -it airflow-scheduler-pod-name -- /bin/bash" 

I looked up the environment variables with this command( "env" or "export"),  
but they were not there.

**Comment by sayakin0519** [comment]
> > @sayakin0519 - are you running Airflow on EKS or GKE? Have you tried setting Environment variables for all airflow containers in values.yaml? Refer this - https://github.com/apache/airflow/blob/main/chart/values.yaml#L272 ?
> 
> @jagpk - I'm running Airflow on EKS. but i'm using "apache-airflow-providers-google", "apache-airflow-providers-mysql" package in my DAG
> 
> So, Yes. I tried that option like this (Example)
> 
> ```yaml
> airflow: 
>   env: 
>     - name: AIRFLOW_CONN_GOOGLE_CLOUD_DEFAULT
>       value: "google-cloud-platform://extra__google_cloud_platform__key_path=/~~~~~~"
>     - name: AIRFLOW_CONN_MYSQL_MYDBNAME
>       value: "mysql://mydbname:password@mysql"
> ```
> 
> After add that code in airflow-values.yaml and I entered this command again. "./install.sh"
> 
> And I entered the pod with this command and looked at env, but it was not there. "kubectl exec -n airflow -it airflow-scheduler-pod-name -- /bin/bash"
> 
> I looked up the environment variables with this command( "env" or "export"), but they were not there.

@jagpk - Is there any other way? 

I would appreciate your reply.

Thanks.

**Comment by sayakin0519** [comment]
I solved this problem.

```YAML
# I deleted first line "airflow: " 
secret:
  - envName: AIRFLOW_CONN_GOOGLE_CLOUD_DEFAULT
    secretName: airflow-conn-google-cloud-default
    secretKey: AIRFLOW_CONN_GOOGLE_CLOUD_DEFAULT

extraSecrets: 
  airflow-conn-google-cloud-default:
    data: |
      AIRFLOW_CONN_GOOGLE_CLOUD_DEFAULT: 'base64 encoding string'
```

This is the link I referenced. 
https://github.com/apache/airflow/blob/main/docs/helm-chart/adding-connections-and-variables.rst#connections-and-sensitive-environment-variables 

Thanks.
